import os
import sys
import json
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
SRC_DIR = PROJECT_ROOT / "src"
# Use .env directory with a .env file inside it
ENV_DIR = PROJECT_ROOT / ".env"
ENV_PATH = ENV_DIR / ".env"
EXTRACONFIG_PATH = SRC_DIR / "extraconfig.py"
TOKENHELPER_PATH = SRC_DIR / "tokenhelper.py"

def prompt(prompt_text, default=""):
    val = input(f"{prompt_text} " + (f"[{default}] " if default else ""))
    return val.strip() or default

def confirm(prompt_text, default=True):
    yn = "Y/n" if default else "y/N"
    val = input(f"{prompt_text} ({yn}): ").strip().lower()
    if val == "":
        return default
    return val in ("y", "yes")

def write_env(bot_token, drive_token_b64):
    # ensure .env directory exists
    ENV_DIR.mkdir(parents=True, exist_ok=True)
    lines = []
    if bot_token is not None:
        lines.append(f'BOT_TOKEN="{bot_token}"')
    if drive_token_b64 is not None:
        lines.append(f'DRIVE_TOKEN_B64="{drive_token_b64}"')
    ENV_PATH.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
    print(f"Written .env > {ENV_PATH}")

def write_extraconfig(bot_owner, backup_folder, test_server):
    content = f"""# filepath: {EXTRACONFIG_PATH}
# autogenerated by startbot.py — edit carefully

EXT_BLACKLIST = (".mp4", ".webm", ".MP4", ".WEBM", ".mp3", ".ogg", ".wav", ".mov", ".zip", ".7z", ".rar", ".db", ".exe", ".msi")
BOT_OWNER = int({bot_owner})
BACKUP_GDRIVE_FOLDER_ID = "{backup_folder}"
TEST_SERVER = int({test_server})
FORBIDDEN_GUILDS = {{}}
FORBIDDEN_USERS = {{}}
MAX_JPEG_RECURSIONS = 15
MAX_JPEG_QUALITY = 4096
"""
    EXTRACONFIG_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote extraconfig > {EXTRACONFIG_PATH}")

def run_tokenhelper():
    if not TOKENHELPER_PATH.exists():
        print("tokenhelper.py not found in src/ — skipping token helper run.")
        return False
    print("About to run tokenhelper.py to obtain Drive token. This may open a browser and require you to authenticate.")
    if not confirm("Proceed to run tokenhelper.py now?"):
        print("Skipped running tokenhelper.py.")
        return False
    # Run tokenhelper.py with same Python interpreter
    try:
        subprocess.run([sys.executable, str(TOKENHELPER_PATH)], check=True)
        print("tokenhelper.py finished.")
        return True
    except subprocess.CalledProcessError as e:
        print(f"tokenhelper.py exited with error: {e}")
        return False

def main():
    print("One-time setup for Flurazide — will write project .env (in .env/), and src/extraconfig.py")
    # .env directory & file
    if ENV_PATH.exists():
        if not confirm(f".env file already exists at {ENV_PATH}. Overwrite?"):
            print("Keeping existing .env")
            env_bot = None
            env_drive = None
        else:
            env_bot = prompt("Enter your BOT_TOKEN (leave blank for placeholder):", "")
            env_drive = prompt("Enter DRIVE_TOKEN_B64 (leave blank if you will run tokenhelper):", "")
            write_env(env_bot or "", env_drive or "")
    else:
        # create folder if needed and write
        bot_token = prompt("Enter your BOT_TOKEN (leave blank for placeholder):", "")
        drive_token = prompt("Enter DRIVE_TOKEN_B64 (leave blank if you will run tokenhelper):", "")
        write_env(bot_token or "", drive_token or "")

    # extraconfig
    if EXTRACONFIG_PATH.exists():
        if not confirm(f"extraconfig.py already exists at {EXTRACONFIG_PATH}. Overwrite?"):
            print("Keeping existing extraconfig.py")
        else:
            bot_owner = int(prompt("Enter BOT_OWNER user ID (integer):", "853154444850364417"))
            backup_id = prompt("Enter BACKUP_GDRIVE_FOLDER_ID:", "1Frrg3F-RBczRC4yitQT1ehhULZDCUXbN")
            test_server = int(prompt("Enter TEST_SERVER ID (integer):", "1240438418388029460"))
            write_extraconfig(bot_owner, backup_id, test_server)
    else:
        bot_owner = int(prompt("Enter BOT_OWNER user ID (integer):", "853154444850364417"))
        backup_id = prompt("Enter BACKUP_GDRIVE_FOLDER_ID:", "1Frrg3F-RBczRC4yitQT1ehhULZDCUXbN")
        test_server = int(prompt("Enter TEST_SERVER ID (integer):", "1240438418388029460"))
        write_extraconfig(bot_owner, backup_id, test_server)

    # Optionally run tokenhelper
    if TOKENHELPER_PATH.exists():
        _ = run_tokenhelper()
    else:
        print("tokenhelper.py not present. If you need to generate DRIVE_TOKEN_B64, add tokenhelper.py to src/ or manually set DRIVE_TOKEN_B64 in .env/.env.")

    print("One-time setup complete. You can now run the bot as usual.")

if __name__ == "__main__":
    main()